stages:
  - build

build_using_docker:
  stage: build
  except:
    - tags
  image: docker:19.03.12
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - |
      docker build --cache-from $CI_REGISTRY_IMAGE:latest \
      --tag $CI_REGISTRY_IMAGE:debug-$CI_COMMIT_SHORT_SHA \
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA \
      --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:debug-$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

build_tags_using_docker:
  stage: build
  only:
    - tags
  image: docker:19.03.12
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - |
      docker build --cache-from $CI_REGISTRY_IMAGE:latest \
      --tag $CI_REGISTRY_IMAGE:debug-$CI_COMMIT_TAG \
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG \
      --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:debug-$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
