stages:
  - build
  - docker

build:
  stage: build
  image: clux/muslrust:1.45.2
  script:
    - rustup target add x86_64-unknown-linux-musl
    - cargo build --target x86_64-unknown-linux-musl
    - cargo build --target x86_64-unknown-linux-musl --release
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/doggo

docker_image:
  stage: docker
  dependencies:
    - build
  except:
    refs:
      - tags
    changes:
      - "README.md"
      - "LICENSE.txt"
  image: docker:19.03.12
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - pwd
    - "echo CI_PROJECT_DIR: ${CI_PROJECT_DIR}"
    - ls -l ${CI_PROJECT_DIR}/target/x86_64-unknown-linux-musl/release/
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - |
      docker build --cache-from $CI_REGISTRY_IMAGE:latest \
      --build-arg CI_PROJECT_DIR=${CI_PROJECT_DIR} \
      --tag $CI_REGISTRY_IMAGE:debug-$CI_COMMIT_SHORT_SHA \
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA \
      --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:debug-$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

docker_tagged_image:
  stage: docker
  dependencies:
    - build
  only:
    - tags
  image: docker:19.03.12
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest
      --build-arg CI_PROJECT_DIR=${CI_PROJECT_DIR}
      --tag $CI_REGISTRY_IMAGE:debug-$CI_COMMIT_TAG
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:debug-$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
